config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
  },
    path: "/",
    path_names: { sign_in: 'login',
                  sign_out: 'logout'
                  },
    :skip => 'registration'

  devise_scope :user do
    authenticated :user do
      root to: 'user_dashboard#index',  as: :authenticated_user_root
      resources :users, except: :show
      resources :account_banks
      resources :agency_banks

      get '/transaction' => 'transaction#index'

      #DEPOSITO
      get '/deposit' => 'transaction#deposit'
      post '/deposit' => 'transaction#send_deposit'
      #SAQUE
      get '/withdrawal' => 'transaction#withdrawal'
      post '/withdrawal' => 'transaction#send_withdrawal'
      #Money transfer
      get '/money_transfer' => 'transaction#money_transfer'
      post '/money_transfer' => 'transaction#send_money_transfer'
      #
      post 'account/suggestion' => 'transaction#suggestion'


      patch 'cash_back/:transaction_id' => 'transaction#cash_back', as: :cash_back

    end
    unauthenticated :users do
      root to: "users/sessions#new", as: :unauthenticated_user_root
    end
  end

end

app/models/account_bank.rb
class AccountBank < ApplicationRecord
  belongs_to :agency_bank, -> { with_deleted }

  validates :number_account, presence: true, uniqueness: true,
    format: { with: /\A\d+\z/, message: "deve ser somente números." }

  validates :limit, presence: true, uniqueness: true, numericality: {only_float: true}
  has_many :transactions
  acts_as_paranoid

  def saldo
    self.transactions.where(transaction_type: :transfer_in).sum(:price) +
      self.transactions.where(transaction_type: :cash_back_in).sum(:price) +
      self.transactions.where(transaction_type: :deposit).sum(:price) -
      self.transactions.where(transaction_type: :withdrawal).sum(:price) -
      self.transactions.where(transaction_type: :cash_back_out).sum(:price) -
      self.transactions.where(transaction_type: :transfer_out).sum(:price)
  end

end

app/controllers/account_banks_controller.rb
class AccountBanksController < BaseController
  before_action :set_account_bank, only: [:show, :edit, :update, :destroy]

  # GET /account_banks
  # GET /account_banks.json
  def index
    @account_banks = params[:agency_id].nil? ? AccountBank.all : AccountBank.includes(:agency_bank).where(agency_banks: {id: params[:agency_id]})
  end

  # GET /account_banks/1
  # GET /account_banks/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: TransactionDatatable.new(view_context, {query: @account_bank.transactions}) }
    end
  end

  # GET /account_banks/new
  def new
    @account_bank = AccountBank.new
  end

  # GET /account_banks/1/edit
  def edit
  end

  # POST /account_banks
  # POST /account_banks.json
  def create
    @account_bank = AccountBank.new(account_bank_params)

    respond_to do |format|
      if @account_bank.save
        format.html { redirect_to account_banks_path, notice: 'Conta foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @account_bank }
      else
        format.html { render :new }
        format.json { render json: @account_bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_banks/1
  # PATCH/PUT /account_banks/1.json
  def update
    respond_to do |format|
      if @account_bank.update(account_bank_params)
        format.html { redirect_to account_banks_path, notice: 'Conta foi editada com sucesso.' }
        format.json { render :show, status: :ok, location: @account_bank }
      else
        format.html { render :edit }
        format.json { render json: @account_bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_banks/1
  # DELETE /account_banks/1.json
  def destroy
    @account_bank.destroy
    respond_to do |format|
      format.html { redirect_to account_banks_url, notice: 'Conta foi deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_account_bank
    @account_bank = AccountBank.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def account_bank_params
    params.require(:account_bank).permit(:agency_bank_id, :number_account, :limit)
  end
end

app/helpers/account_banks_helper.rb
module AccountBanksHelper
end

app/views/account_banks/_form.html.erb
<div class="panel-body">
   <%= form_with(model: account_bank, local: true) do |f| %>
     <% if account_bank.errors.any? %>
      <script>
         $(document).ready(function() {
          noty({text: ' <%= pluralize(account_bank.errors.count, "erro", "erros") %> encontrados: </br><ul><% account_bank.errors.each do |attr,message| %><li><%=attr%> <%= message %></li><% end %></ul>', layout: 'bottom', type: 'warning', timeout: 4000});
         });
      </script>
    <% end %>


      <div class="form-group row">
         <label class="col-sm-3 col-form-label text-right">Agência</label>
         <div class="col-sm-6">
             <%= f.select(:agency_bank_id, AgencyBank.all.collect{|k| [k.number_agency, k.id] }, {include_blank: 'Selecione a agência'}, class: "form-control select2", :id => 'federation') %>
         </div>
      </div>
      <div class="form-group row">
         <label class="col-sm-3 col-form-label text-right">Número da conta</label>
         <div class="col-sm-6">
            <%= f.text_field :number_account, class: 'form-control' %>
         </div>
      </div>

      <div class="form-group row">
         <label class="col-sm-3 col-form-label text-right">Limite</label>
         <div class="col-sm-6">
            <%= f.text_field :limit, class: 'form-control' %>
         </div>
      </div>


      <div class="form-group row">
         <div class="col-sm-6">
            <button type="submit" class="btn btn-space btn-primary ">Salvar</button>
            <%= link_to account_banks_path do %><button type="button" class="btn btn-space btn-secondary">Voltar</button><% end %>
         </div>
      </div>
   <% end %>
</div>

app/views/account_banks/edit.html.erb
<div class="main-content container">
	<div class="row">
	  <div class="col-md-12">
	    <div class="panel panel-default">
	      <div class="panel-heading panel-heading-divider">Editar conta bancária<span class="panel-subtitle">Edite os campos e salve para realizar a alteração</span></div>
	      	<%= render 'form', account_bank: @account_bank %>
	    </div>
	  </div>
	</div>
</div>

app/views/account_banks/index.html.erb
  <div class="main-content container">
        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default panel-table">
              <div class="panel-heading"><span class="box-title">Listagem de Contas Bancárias</span>
                <div class="pull-right">
                 
                  <div class="tools pull-right" style="margin-top: -8px"><%= link_to new_account_bank_path do %><button class="btn btn-rounded btn-primary">Nova Conta</button><% end %></div>
               </div>
              </div>
              <div class="panel-body">
              
                  <table id="table_inter" class="table table-striped table-bordered dt-responsive nowrap display"  cellspacing="0" width="100%">
                  <thead>
                    <tr>
                      <th>Agência</th>
                      <th>Número da conta</th>
                      <th>Limite</th>
                      <th>Saldo</th>
                      <th class="noExport"></th>
                      <th class="noExport"></th>
                      <th class="noExport"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @account_banks.each do |account_bank| %>
                    <tr class="odd gradeX">

                      <td><%= account_bank.agency_bank.number_agency %></td>
                      <td><%= account_bank.number_account %></td>
                      <td><%= number_to_currency(account_bank.limit) %></td>
                      <td><%= number_to_currency(account_bank.saldo) %></td>

                      <td class="actions"><%= link_to account_bank_path(account_bank), class: 'icon' do %><i class="s7-look"></i> Ver Movimentações<% end %></td>

                      <td class="actions"><%= link_to edit_account_bank_path(account_bank), class: 'icon' do %><i class="s7-settings"></i> Editar<% end %></td>

                      <td class="actions"><%= link_to account_bank, method: :delete, data: { confirm: 'Deseja realmente apagar a conta?' }, class: 'icon' do %><i class="s7-trash"></i>Apagar<% end %> 

                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/account_banks/new.html.erb
<div class="main-content container">
	<div class="row">
	  <div class="col-md-12">
	    <div class="panel panel-default">
	      <div class="panel-heading panel-heading-divider">Nova conta bancária<span class="panel-subtitle">Preencha os campos e salve para realizar um novo cadastro</span></div>
	      	<%= render 'form', account_bank: @account_bank %>
	    </div>
	  </div>
	</div>
</div>

app/views/account_banks/show.html.erb
      <div class="main-content container">
        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default panel-table">
              <div class="panel-heading"><span class="box-title">Movimentações - Conta <%= @account_bank.number_account %> - Agência <%= @account_bank.agency_bank.number_agency %></span>
                <div class="pull-right">
                 
                  <div class="tools pull-right" style="margin-top: -8px"><%= link_to account_banks_path do %><button class="btn btn-rounded btn-primary">Voltar</button><% end %></div>
               </div>
              </div>
              <div class="panel-body">
          
                  <table id="transaction-table", data-source="<%= account_bank_path(format: :json) %>" class="table table-striped table-bordered dt-responsive nowrap display"  cellspacing="0" width="100%">


                  <thead>
                    <tr>
                      <th>Data</th>
                      <th>Tipo</th>
                      <th>Valor</th>
                      <th>Usuário</th>
                      <th class="noExport"></th>
                    </tr>
                  </thead>
                  <tbody>
                    
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>