config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
  },
    path: "/",
    path_names: { sign_in: 'login',
                  sign_out: 'logout'
                  },
    :skip => 'registration'

  devise_scope :user do
    authenticated :user do
      root to: 'user_dashboard#index',  as: :authenticated_user_root
      resources :users, except: :show
      resources :account_banks
      resources :agency_banks

      get '/transaction' => 'transaction#index'

      #DEPOSITO
      get '/deposit' => 'transaction#deposit'
      post '/deposit' => 'transaction#send_deposit'
      #SAQUE
      get '/withdrawal' => 'transaction#withdrawal'
      post '/withdrawal' => 'transaction#send_withdrawal'
      #Money transfer
      get '/money_transfer' => 'transaction#money_transfer'
      post '/money_transfer' => 'transaction#send_money_transfer'
      #
      post 'account/suggestion' => 'transaction#suggestion'


      patch 'cash_back/:transaction_id' => 'transaction#cash_back', as: :cash_back

    end
    unauthenticated :users do
      root to: "users/sessions#new", as: :unauthenticated_user_root
    end
  end

end

app/views/layouts/shared/_top_menu.html.erb
      <nav class="navbar navbar-expand-lg mai-sub-header">
         <div class="container">
            <!-- Mega Menu structure-->
            <nav class="navbar navbar-expand-md">
               <button type="button" data-toggle="collapse" data-target="#mai-navbar-collapse" aria-controls="#mai-navbar-collapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler hidden-md-up collapsed">
                  <div class="icon-bar"><span></span><span></span><span></span></div>
               </button>
               <div id="mai-navbar-collapse" class="navbar-collapse collapse mai-nav-tabs">
                  <ul class="nav navbar-nav">
                     <li class="nav-item parent <%=menu_open("/")%>">
                        <%= link_to authenticated_user_root_path, class: 'nav-link' do %><span class="icon s7-home"></span><span>Home</span><% end %>
                     </li>
                     <li class="nav-item parent <%=menu_open("/users")%>">
                        <%= link_to users_path, class: 'nav-link' do %><span class="icon s7-users"></span><span>Usuários</span><% end %>
                     </li>
                     <li class="nav-item parent <%=menu_open("/agency_banks")%>">
                        <%= link_to agency_banks_path, class: 'nav-link' do %><span class="icon s7-home"></span><span>Agências Bancárias</span><% end %>
                     </li>
                     <li class="nav-item parent <%=menu_open("/account_banks")%>">
                        <%= link_to account_banks_path, class: 'nav-link' do %><span class="icon s7-id"></span><span>Contas Bancárias</span><% end %>
                     </li>
                     <li class="nav-item parent <%=menu_open("/transaction")%>">
                        <%= link_to transaction_path, class: 'nav-link' do %><span class="icon s7-repeat"></span><span>Movimentações</span><% end %>
                     </li>
                  </ul>
               </div>
            </nav>
         </div>
      </nav>

      