config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
  },
    path: "/",
    path_names: { sign_in: 'login',
                  sign_out: 'logout'
                  },
    :skip => 'registration'

  devise_scope :user do
    authenticated :user do
      root to: 'user_dashboard#index',  as: :authenticated_user_root
      resources :users, except: :show
      resources :account_banks
      resources :agency_banks

      get '/transaction' => 'transaction#index'

      #DEPOSITO
      get '/deposit' => 'transaction#deposit'
      post '/deposit' => 'transaction#send_deposit'
      #SAQUE
      get '/withdrawal' => 'transaction#withdrawal'
      post '/withdrawal' => 'transaction#send_withdrawal'
      #Money transfer
      get '/money_transfer' => 'transaction#money_transfer'
      post '/money_transfer' => 'transaction#send_money_transfer'
      #
      post 'account/suggestion' => 'transaction#suggestion'


      patch 'cash_back/:transaction_id' => 'transaction#cash_back', as: :cash_back

    end
    unauthenticated :users do
      root to: "users/sessions#new", as: :unauthenticated_user_root
    end
  end

end

app/controllers/transaction_controller.rb
class TransactionController < BaseController

  before_action :set_account_bank, only: [:send_deposit, :send_withdrawal, :send_money_transfer]
  before_action :set_account_bank_destination, only: :send_money_transfer

  def index
  end

  def deposit
    @transaction = Transaction.new
  end

  def send_deposit
    @transaction = Transaction.new(account_bank_id: @find_account_bank.id, price: params[:price], transaction_type: :deposit, user_id: @user.id)
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_path, notice: 'Depósito efetuado com sucesso.' }
        format.json { render :deposit, status: :created }
      else
        format.html { render :deposit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def withdrawal
    @transaction = Transaction.new
  end

  def send_withdrawal
    @transaction = Transaction.new(account_bank_id: @find_account_bank.id, price: params[:price], transaction_type: :withdrawal, user_id: @user.id)
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_path, notice: 'Saque efetuado com sucesso.' }
        format.json { render :deposit, status: :created }
      else
        format.html { render :withdrawal }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def cash_back
    @t = Transaction.find_by_id(params[:transaction_id])
    if !@t.nil? && !@t.cash_out
      if @t.transaction_type == "deposit"
        @t.update_attribute('cash_out', true)
        Transaction.create!(account_bank_id: @t.account_bank_id, price: @t.price, transaction_type: :cash_back_out, user_id: @user.id)
        redirect_to account_bank_path(@t.account_bank_id), alert: "Sucesso"
      elsif @t.transaction_type == "transfer_out"
        @transaction = ActiveRecord::Base.transaction do
          begin
            @t.update_attribute('cash_out', true)
            #adicionar na conta atual
            Transaction.create!(account_bank_id: @t.account_bank_id, price: @t.price, transaction_type: :cash_back_in, user_id: @user.id)
            #remover da outra conta
            Transaction.create!(account_bank_id: @t.destination_account_bank_id, price: @t.price, transaction_type: :cash_back_out, user_id: @user.id)
          rescue  => ex
            # p ex
            @t.update_attribute('cash_out', false)
            raise ActiveRecord::Rollback
          end
        end
        if @transaction
          redirect_back(fallback_location: authenticated_user_root_path, alert: "Sucesso")
        else
          redirect_back(fallback_location: authenticated_user_root_path, alert: "Erro. Verifique o limite das contas envolvidas")
        end
      end
    else
      redirect_to account_bank_path(@t.account_bank_id), alert: "Erro! O estorno já foi realizado"
    end
  end

  def money_transfer
    @transaction = Transaction.new
  end

  def send_money_transfer
    #INSERIR
    @transaction_to = Transaction.new(account_bank_id: @find_account_bank_d.id, price: params[:price], transaction_type: :transfer_in, user_id: @user.id, destination_account_bank_id: @find_account_bank.id )
    #RETIRAR
    @transaction_from = Transaction.new(account_bank_id: @find_account_bank.id, price: params[:price], transaction_type: :transfer_out, user_id: @user.id, destination_account_bank_id: @find_account_bank_d.id )

    @transaction = ActiveRecord::Base.transaction do
      begin
        @transaction_to.save!
        @transaction_from.save!
        @transaction = true
      rescue  => ex
        @transaction = false
        raise ActiveRecord::Rollback
      end
    end

    if @transaction
      redirect_to money_transfer_path, notice: 'Transferência efetuada com sucesso.'
    else
      redirect_to money_transfer_path, notice: 'Houve um erro ao realizar a transferência. Verifique o saldo e o limite das respectivas contas'
    end
  end

  def suggestion
    @account = AccountBank.find_by_number_account(params[:number_account])
    unless  @account.nil?
      render html: ("Ag: #{@account.agency_bank.number_agency}, Saldo: #{view_context.number_to_currency(@account.saldo)}, Limite: #{view_context.number_to_currency(@account.limit)}").html_safe
    else
      render html: ("Conta não encontrada.").html_safe
    end
  end

  private

  def set_account_bank
    @find_account_bank = AccountBank.find_by_number_account(params[:number_account])
    if @find_account_bank.nil?
      #CONTA NAO ENCONTRADA
      redirect_back(fallback_location: authenticated_user_root_path, alert: "Não foi possível encontrar a conta bancária (De).")
    end
  end


  def set_account_bank_destination
    @find_account_bank_d = AccountBank.find_by_number_account(params[:number_account_destination])
    if @find_account_bank_d.nil?
      #CONTA NAO ENCONTRADA
      redirect_back(fallback_location: authenticated_user_root_path, alert: "Não foi possível encontrar a conta bancária (Para).")
    end
  end


end

app/helpers/transaction_helper.rb
module TransactionHelper
  #MODAL
  def infos_transfer(transaction)
    if transaction.transaction_type == "transfer_in"
      "Dinheiro recebido da conta #{transaction.destination_account_bank.number_account}, agência #{transaction.destination_account_bank.agency_bank.number_agency}"
    elsif transaction.transaction_type == "transfer_out"
      "Dinheiro enviado para a conta #{transaction.destination_account_bank.number_account}, agência #{transaction.destination_account_bank.agency_bank.number_agency}"
    end
  end

  def cash_back_button(transaction)
    if ["deposit", "transfer_out"].include? transaction.transaction_type
      if transaction.cash_out
        "ESTORNADO"
      else
        link_to cash_back_path(transaction), class: 'icon', method: :patch, data: { confirm: "Deseja realmente estonar #{number_to_currency(transaction.price)}?" } do
          content_tag(:i, "", class: "s7-trash") + "Estornar"
        end
      end
    end
  end

  def transaction_type_view(transaction)
    if ["transfer_in", "transfer_out"].include? transaction.transaction_type
      link_to "", data: { confirm: "#{infos_transfer(transaction)}" } do
        Transaction.human_enum_name(:transaction_types, transaction.transaction_type)
      end
    else
      Transaction.human_enum_name(:transaction_types, transaction.transaction_type)
    end
  end
end

app/views/transaction/deposit.html.erb
<div class="main-content container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading panel-heading-divider">Efetuar depósito</div>
          <div class="panel-body">
             <%= form_with url: deposit_path, local: true do |f| %>

             <% if @transaction.errors.any? %>
                <script>
                   $(document).ready(function() {
                    noty({text: ' <%= pluralize(@transaction.errors.count, "erro", "erros") %> encontrados: </br><ul><% @transaction.errors.each do |attr,message| %><li><%=attr%> <%= message %></li><% end %></ul>', layout: 'bottom', type: 'warning', timeout: 4000});
                   });
                </script>
              <% end %>


                <div class="form-group row">
                   <label class="col-sm-3 col-form-label text-right">Número da Conta</label>
                   <div class="col-sm-6">
                      <%= f.number_field :number_account, class: 'form-control', id: "account"  %>
                      <small id="receber_infos"></small>
                   </div>
                </div>

                <div class="form-group row">
                   <label class="col-sm-3 col-form-label text-right">Valor</label>
                   <div class="col-sm-6">
                      <%= f.text_field :price, class: 'form-control' %>
                   </div>
                </div>
               
                <div class="form-group row">
                   <div class="col-sm-6">
                      <button type="submit" class="btn btn-space btn-primary ">Salvar</button>
                      <%#= link_to agency_banks_path do %><button type="button" class="btn btn-space btn-secondary">Voltar</button><%# end %>
                   </div>
                </div>
             <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/transaction/index.html.erb
<div class="main-content container">
        <div class="row">
          <div class="col-md-12">
            <div class="panel panel-default">
              <div class="panel-heading panel-heading-divider">Ações<span class="panel-subtitle">O que você deseja fazer?</span></div>
              <div class="panel-body">
               
                <div class="mt-1 mb-1 text-center">
                  <%=link_to money_transfer_path do %>
                  <button class="btn btn-space btn-primary btn-big"><i class="icon s7-home"></i> transferências  </button>
                  <% end %>
                  <%=link_to deposit_path do %>
                  <button class="btn btn-space btn-info btn-big"><i class="icon s7-diamond"></i> Deposito </button><% end %>
                  <%=link_to withdrawal_path do %>
                  <button class="btn btn-space btn-warning btn-big"><i class="icon s7-mail"></i> Saque </button>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/transaction/money_transfer.html.erb
<div class="main-content container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading panel-heading-divider">Efetuar Transferência</div>
          <div class="panel-body">
             <%= form_with url: money_transfer_path, local: true do |f| %>


                <div class="form-group row">
                   <label class="col-sm-3 col-form-label text-right">Número da Conta (De)</label>
                   <div class="col-sm-6">
                      <%= f.number_field :number_account, class: 'form-control', id: "account" %>
                      <small id="receber_infos"></small>
                   </div>
                </div>

                <div class="form-group row">
                   <label class="col-sm-3 col-form-label text-right">Número da Conta (Para)</label>
                   <div class="col-sm-6">
                      <%= f.number_field :number_account_destination, class: 'form-control', id: "account_d" %>
                      <small id="receber_infos_d"></small>
                   </div>
                </div>

                <div class="form-group row">
                   <label class="col-sm-3 col-form-label text-right">Valor</label>
                   <div class="col-sm-6">
                      <%= f.text_field :price, class: 'form-control' %>
                   </div>
                </div>
               
                <div class="form-group row">
                   <div class="col-sm-6">
                      <button type="submit" class="btn btn-space btn-primary ">Salvar</button>
                      <%#= link_to agency_banks_path do %><button type="button" class="btn btn-space btn-secondary">Voltar</button><%# end %>
                   </div>
                </div>
             <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/transaction/withdrawal.html.erb
<div class="main-content container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading panel-heading-divider">Efetuar saque</div>
          <div class="panel-body">
             <%= form_with url: withdrawal_path, local: true do |f| %>

             <% if @transaction.errors.any? %>
                <script>
                   $(document).ready(function() {
                    noty({text: ' <%= pluralize(@transaction.errors.count, "erro", "erros") %> encontrados: </br><ul><% @transaction.errors.each do |attr,message| %><li><%=attr%> <%= message %></li><% end %></ul>', layout: 'bottom', type: 'warning', timeout: 4000});
                   });
                </script>
              <% end %>


                <div class="form-group row">
                   <label class="col-sm-3 col-form-label text-right">Número da Conta</label>
                   <div class="col-sm-6">
                      <%= f.number_field :number_account, class: 'form-control', id: "account" %>
                      <small id="receber_infos"></small>
                   </div>
                </div>

                <div class="form-group row">
                   <label class="col-sm-3 col-form-label text-right">Valor</label>
                   <div class="col-sm-6">
                      <%= f.text_field :price, class: 'form-control' %>
                   </div>
                </div>
               
                <div class="form-group row">
                   <div class="col-sm-6">
                      <button type="submit" class="btn btn-space btn-primary ">Salvar</button>
                      <%#= link_to agency_banks_path do %><button type="button" class="btn btn-space btn-secondary">Voltar</button><%# end %>
                   </div>
                </div>
             <% end %>
          </div>
      </div>
    </div>
  </div>
</div>