config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
  },
    path: "/",
    path_names: { sign_in: 'login',
                  sign_out: 'logout'
                  },
    :skip => 'registration'

  devise_scope :user do
    authenticated :user do
      root to: 'user_dashboard#index',  as: :authenticated_user_root
      resources :users, except: :show
      resources :account_banks
      resources :agency_banks

      get '/transaction' => 'transaction#index'

      #DEPOSITO
      get '/deposit' => 'transaction#deposit'
      post '/deposit' => 'transaction#send_deposit'
      #SAQUE
      get '/withdrawal' => 'transaction#withdrawal'
      post '/withdrawal' => 'transaction#send_withdrawal'
      #Money transfer
      get '/money_transfer' => 'transaction#money_transfer'
      post '/money_transfer' => 'transaction#send_money_transfer'
      #
      post 'account/suggestion' => 'transaction#suggestion'


      patch 'cash_back/:transaction_id' => 'transaction#cash_back', as: :cash_back

    end
    unauthenticated :users do
      root to: "users/sessions#new", as: :unauthenticated_user_root
    end
  end

end

app/models/agency_bank.rb
class AgencyBank < ApplicationRecord
  #VALIDACOES
  validates :number_agency, presence: true, uniqueness: true,
    format: { with: /\A\d+\z/, message: "deve ser somente números." }
  validates :address, presence: true

  has_many :account_banks
  acts_as_paranoid
end

app/controllers/agency_banks_controller.rb
class AgencyBanksController < BaseController
  before_action :set_agency_bank, only: [:show, :edit, :update, :destroy]

  # GET /agency_banks
  # GET /agency_banks.json
  def index
    @agency_banks = AgencyBank.all
  end

  # GET /agency_banks/1
  # GET /agency_banks/1.json
  def show
  end

  # GET /agency_banks/new
  def new
    @agency_bank = AgencyBank.new
  end

  # GET /agency_banks/1/edit
  def edit
  end

  # POST /agency_banks
  # POST /agency_banks.json
  def create
    @agency_bank = AgencyBank.new(agency_bank_params)

    respond_to do |format|
      if @agency_bank.save
        format.html { redirect_to agency_banks_path, notice: 'Agência foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @agency_bank }
      else
        format.html { render :new }
        format.json { render json: @agency_bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agency_banks/1
  # PATCH/PUT /agency_banks/1.json
  def update
    respond_to do |format|
      if @agency_bank.update(agency_bank_params)
        format.html { redirect_to agency_banks_path, notice: 'Agência foi editada com sucesso.' }
        format.json { render :show, status: :ok, location: @agency_bank }
      else
        format.html { render :edit }
        format.json { render json: @agency_bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agency_banks/1
  # DELETE /agency_banks/1.json
  def destroy
    @agency_bank.destroy
    respond_to do |format|
      format.html { redirect_to agency_banks_url, notice: 'Agência foi apagadas com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency_bank
      @agency_bank = AgencyBank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_bank_params
      params.require(:agency_bank).permit(:number_agency, :address)
    end
end

app/helpers/agency_banks_helper.rb
module AgencyBanksHelper
end

app/views/agency_banks/_form.html.erb
<div class="panel-body">
   <%= form_with(model: agency_bank, local: true) do |f| %>
     <% if agency_bank.errors.any? %>
      <script>
         $(document).ready(function() {
          noty({text: ' <%= pluralize(agency_bank.errors.count, "erro", "erros") %> encontrados: </br><ul><% agency_bank.errors.each do |attr,message| %><li><%=attr%> <%= message %></li><% end %></ul>', layout: 'bottom', type: 'warning', timeout: 4000});
         });
      </script>
    <% end %>


      <div class="form-group row">
         <label class="col-sm-3 col-form-label text-right">Número da Agência</label>
         <div class="col-sm-6">
            <%= f.number_field :number_agency, class: 'form-control' %>
         </div>
      </div>
      <div class="form-group row">
         <label class="col-sm-3 col-form-label text-right">Endereço</label>
         <div class="col-sm-6">
            <%= f.text_field :address,class: 'form-control' %>
         </div>
      </div>
      <div class="form-group row">
         <div class="col-sm-6">
            <button type="submit" class="btn btn-space btn-primary ">Salvar</button>
            <%= link_to agency_banks_path do %><button type="button" class="btn btn-space btn-secondary">Voltar</button><% end %>
         </div>
      </div>
   <% end %>
</div>

app/views/agency_banks/edit.html.erb
<div class="main-content container">
	<div class="row">
	  <div class="col-md-12">
	    <div class="panel panel-default">
	      <div class="panel-heading panel-heading-divider">Editar agência<span class="panel-subtitle">Edite os campos e salve para realizar a alteração</span></div>
	      	<%= render 'form', agency_bank: @agency_bank %>
	    </div>
	  </div>
	</div>
</div>

app/views/agency_banks/index.html.erb
  <div class="main-content container">
        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default panel-table">
              <div class="panel-heading"><span class="box-title">Listagem de agências</span>
                <div class="pull-right">
                 
                  <div class="tools pull-right" style="margin-top: -8px"><%= link_to new_agency_bank_path do %><button class="btn btn-rounded btn-primary">Nova agência</button><% end %></div>
               </div>
              </div>
              <div class="panel-body">
              
                  <table id="table_inter" class="table table-striped table-bordered dt-responsive nowrap display"  cellspacing="0" width="100%">
                  <thead>
                    <tr>
                      <th>Número da agência</th>
                      <th>Endereço</th>
                      <th></th>
                      <th></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @agency_banks.each do |agency_bank| %>
                    <tr class="odd gradeX">
                      <td><%= agency_bank.number_agency %></td>
                      <td><%= agency_bank.address %></td>
                      <td class="actions"><%= link_to account_banks_path(:agency_id => agency_bank.id), class: 'icon' do %><i class="s7-look"></i> Ver Contas<% end %></td>

                      <td class="actions"><%= link_to edit_agency_bank_path(agency_bank), class: 'icon' do %><i class="s7-settings"></i> Editar<% end %></td>

                      <td class="actions"><%= link_to agency_bank, method: :delete, data: { confirm: 'Deseja realmente apagar a agência?' }, class: 'icon' do %><i class="s7-trash"></i>Apagar<% end %> 

                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/agency_banks/new.html.erb
<div class="main-content container">
	<div class="row">
	  <div class="col-md-12">
	    <div class="panel panel-default">
	      <div class="panel-heading panel-heading-divider">Nova agência<span class="panel-subtitle">Preencha os campos e salve para realizar um novo cadastro</span></div>
	      	<%= render 'form', agency_bank: @agency_bank %>
	    </div>
	  </div>
	</div>
</div>

app/views/agency_banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number agency:</strong>
  <%= @agency_bank.number_agency %>
</p>

<p>
  <strong>Address:</strong>
  <%= @agency_bank.address %>
</p>

<%= link_to 'Edit', edit_agency_bank_path(@agency_bank) %> |
<%= link_to 'Back', agency_banks_path %>